
name: objc_cache
version: 0.0.1
language: objc
description: Objc cache
public: true
tags:
  - objc
  - cache
inputs:
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  
